# netlify.toml
[build]
  command   = "npm run build"
  publish   = "dist"

[dev]
  # Netlify Dev will listen here (for functions + SPA fallback)
  port       = 8888

  # This is your Vite dev server
  framework  = "vite"
  command    = "npm run dev"
  targetPort = 5173

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

